name: Gemini AI Code Review (Clean)

on:
  # pull_request:
  #   types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      eol_server_type:
        description: 'Test'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - STAGE
          - LIVE
jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gemini AI Review
        uses: freevue/preview
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
